### ISSUE TITLE
Fix card sizing on mobile screen

### ISSUE THREAD

**Issue by AmboMaya** [kowhai-2018/Final-Project#105]
![screen shot 2018-12-09 at 12 44 10 pm 2](https://user-images.githubusercontent.com/12192742/49691853-74f79a80-fbb0-11e8-9e01-9c07f2bbb480.png)
At the moment on a mobile screen, each cards seem to look quite large. I have tried various way to resize the cards without breaking something else. No luck, perhaps someone else can give it ago? 

other related design issues:
* if we can fix the card size to be smaller (when view on mobile screen) maybe the smiley face will be smaller. otherwise we can change icon to fa-2x
* ellipsi sub-menu currently doesn't exactly look like the design (this is the only free one we can get)

**Comment by Jeremy-Jonas** [comment]
Which branch are you viewing these from? If I view the current development branch on my mobile it looks absolutely fine, the cards are the optimum size for a mobile screen and everything is easily readable.
