### ISSUE TITLE
Make i icon on cards change colour on mouse-over

### ISSUE THREAD

**Issue by Jeremy-Jonas** [kowhai-2018/Final-Project#121]
Currently when you mouse-over the i icon in the top right of cards in the app there is no colour change or any indication that it is clickable. Suggest getting it to highlight or change colour like the add section on the bottom of the card.

**Comment by chrislaupama** [comment]
I'm making it so it is what ever is clicked will be in a unique colour.

I'm gonna focus on mobile first and then make it so it's hover-able later down the line.
