### ISSUE TITLE
Fix 'updateDB' script so it doesn't fail on first run

### ISSUE THREAD

**Issue by bryceknz** [kowhai-2018/Final-Project#136]
Currently the updateDB script fails if `dev.sqlite3` doesn't exist, which will happen the first time a user pulls down the project (as I did myself!).

This can be fixed by simply adding a `-f` option to the command, which will ignore any nonexistent files, thereby sending back a `return status` of `0` for `true`. Then the execution will continue as normal, either processing further commands in the script, or returning the cursor focus back to the user in the Linux terminal.

**Comment by CarelS072** [comment]
Amazing will have a quick peek at it now
