### ISSUE TITLE
Remove database seed run from Heroku start script

### ISSUE THREAD

**Issue by Jeremy-Jonas** [kowhai-2018/Final-Project#143]
Need to remove the following line from the Heroku start script to ensure we aren't clearing out the database every time an update is pushed which causes a rebuild.
```
 yarn knex migrate:latest && yarn knex seed:run
```

**Comment by CarelS072** [comment]
To be clear this is for the master deployment and depending on how we want to present

**Comment by CarelS072** [comment]
completed in current pwa build
