### ISSUE TITLE
UI design specs

### ISSUE THREAD

**Issue by chrislaupama** [kowhai-2018/Final-Project#2]
We need to have a design guide for:

- [x] Colours ( primary, secondary, call to action, links etc. )
- [x] Icons
- [x] Button style/s
- [x] Font
- [x] Any other design rules

Once everyone agrees, design a wiki page via issue #6

**Comment by Jeremy-Jonas** [comment]
Colour theme selected and added to wiki

**Comment by Jeremy-Jonas** [comment]
Style guidelines added to wiki page with links to icons and font, sample of colour scheme with hex values for the colours.
