### ISSUE TITLE
Create development branch and set as default origin

### ISSUE THREAD

**Issue by chrislaupama** [kowhai-2018/Final-Project#5]
To ensure we don't have conflicts or anyone accidentally pushing to the master branch, let's set up the development branch and also ensure that all merges to the development branch require a pull request (PR)

- [x] Setup development branch
- [x] Set the development branch as the default origin
- [x] Require all PR's to the development branch to require a review

**Comment by CarelS072** [comment]
Completed , added additional check to perform merge before PR can be performed
