### ISSUE TITLE
Design a prototype/mockup of app using design guides

### ISSUE THREAD

**Issue by chrislaupama** [kowhai-2018/Final-Project#6]
Have a wiki page dedicated to the design specs including all the different types of design guides, colours etc from #2 . 

Relates to #2

**Comment by chrislaupama** [comment]
You can find some design tools for prototype/mockup here: https://github.com/kowhai-2018/Final-Project/wiki/Design-Tools

**Comment by Jeremy-Jonas** [comment]
Proof of app available [here](https://github.com/kowhai-2018/Final-Project/wiki/App-Design)
